version: '3.8'

services:
  mysql:
    image: mysql:5.7.8
    environment:
      - MYSQL_DATABASE=discordbot
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
    ports:
      - '3306:3306'
